name: Build APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ./app/build/outputs/apk/debug/app-debug.apk


